# This file reboots all machines in your inventory, change hosts to reflect the desired section if need be or use the --limit option to only reboot one host
---
- hosts: all
  become: true
  serial: 100

  tasks:
  
    - name: restart server
      shell: /bin/sleep 5 && /sbin/shutdown -r now "Reboot triggered by Ansible"
      async: 1
      poll: 0
      ignore_errors: true

    - name: waiting for the servers to come back
      wait_for:
        port: 22
        state: started
        host: '{{ ansible_ssh_host | default(inventory_hostname) }}'
        delay: 30
        timeout: 1200
        sleep: 10
      become: false
      connection: local

