# This file creates a host file on all hosts based on the inventory file and the domain you set below
# Make sure to put all hosts in the newservers section and uncomment any.  This got messy doing it by section given the various server types with ceph, so its only one section now.  centoOS 7 version still works with centOS 8 and newest ansible 2.9 though.

---
- hosts: newservers
  become: true
  serial: 100

  vars:
    # Set domain here
    primarydomain: "cephclustertest.local"

  tasks:
  
   - name: update host file
     lineinfile:
       dest: /etc/hosts
       regexp: '{{ hostvars[item].ansible_default_ipv4.address }}.*{{ item }} {{item}}.{{primarydomain}}$'
       line: "{{ hostvars[item].ansible_default_ipv4.address }} {{item}} {{item}}.{{primarydomain}}"
       state: present
     with_items: "{{ groups.newservers }}"

