# Sets the hostname to match the inventory shortname

---
- hosts: newservers
  become: true
  serial: 100

  tasks:

     - name: Set hostname
       hostname:
         name: "{{ inventory_hostname_short }}"
