# This is used for pushing vm tools to virtual machines newly added.  I would suggest using the --limit ansible command to select specific hosts

---
- hosts: newservers
  become: true
  serial: 100

  tasks:

    - name: Ensure open-vm-tools is installed
      yum: name=open-vm-tools state=installed

